name: Build Mod

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          
      - name: Add hosts to /etc/hosts
        run: sudo echo "192.99.194.128 export.mcpbot.bspk.rs" | sudo tee -a /etc/hosts

      - name: Setup Gradle 3.10
        uses: gradle/actions/setup-gradle@v4
         
      - name: Build 
        run: gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: meo
          path: build/libs/*-*.jar

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: Build
          files: |
            LICENSE.txt
            ./build/libs/*-*.jar
